### ISSUE TITLE
DOCMAN Feature

### ISSUE THREAD

**Issue by RichJackson** [RichJackson/turbo-laser#35]
Add a new reader for the DOCMAN system, such that

1) metadata can be read from a mysql database
2) from the metadata, a file path is read and loaded as a binary file
3) tika takes over
4) primary key and datestamp partitioning is supported

**Comment by hkkenneth** [comment]
Is this similar to what KCH requested months ago? Actually one project at UCL may need something similar as well.

**Comment by RichJackson** [comment]
Yeah this is for KCH. Let's catch up after the call tomorrow morning

Sent from Yahoo Mail on Android 
 
  On Thu, 2 Feb 2017 at 17:18, Kenneth Lui<notifications@github.com> wrote:   
Is this similar to what KCH requested months ago? Actually one project at UCL may need something similar as well.
